# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for Calculator App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment (optional for testing/linting)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies (if you add a package.json for tooling)
    - name: Install dependencies
      run: npm install

    # Step 4: Run Linting (optional)
    - name: Run Linting
      run: |
        echo "No linting configured yet" # Replace with actual linter commands
        # Example: npx eslint .

    # Step 5: Run Tests (if applicable)
    - name: Run Tests
      run: |
        echo "No tests configured yet" # Replace with test commands
        # Example: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
